// dsh-reelspot client bundle (generated by build.mjs; do not edit directly)
window.__ModuleLoader__.load({
	id: "dsh-reelspot",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		const React = require("react");
		const ReelSpot = (() => {
		  const MIME_CANDIDATES = [
		    { mime: 'video/mp4;codecs=avc1.64001f,mp4a.40.2', ext: 'mp4' },
		    { mime: 'video/mp4;codecs=avc1,mp4a', ext: 'mp4' },
		    { mime: 'video/mp4', ext: 'mp4' },
		    { mime: 'video/webm;codecs=vp9,opus', ext: 'webm' },
		    { mime: 'video/webm;codecs=vp8,opus', ext: 'webm' },
		    { mime: 'video/webm', ext: 'webm' },
		  ]
		
		  const DEFAULTS = {
		    mic: true,               // request the microphone and mix it in
		    webcam: false,           // webcam bubble overlay (needs the compose pipe)
		    webcamSize: 0.18,        // bubble diameter as a fraction of frame width
		    webcamPosition: 'bottom-right', // bottom-right | bottom-left | top-right | top-left
		    webcamMirror: true,      // mirror the webcam (self-view convention)
		    zoom: false,             // cursor-follow zoom pipeline (canvas)
		    zoomFactor: 1.8,         // magnification while the cursor is active
		    zoomIdleMs: 2000,        // idle delay before zooming back out
		    zoomWheel: true,         // Alt+mouse-wheel adjusts the zoom factor live (1x = full view)
		    zoomMax: 3.5,            // wheel-adjustable zoom ceiling
		    zoomStep: 0.2,           // wheel step per notch
		    zoomMinimap: true,       // viewport minimap in the MONITOR window (never in the video)
		    operatorPreview: true,   // live "what is being recorded" monitor window (see below)
		    autoMonitor: true,       // try to open the monitor automatically right after the picker
		    previewWindow: null,     // optional Document PiP window handed in by the caller
		    // Operator preview: callers with a user gesture should open
		    // `documentPictureInPicture.requestWindow()` at click time and pass it as
		    // previewWindow — the core pipes the composed canvas into it, so the
		    // operator sees the exact recorded frame live. A Document PiP window is a
		    // separate top-level window: it is NOT captured when recording this tab.
		    cursorFx: false,         // cursor highlight ring + click ripples (this-tab only)
		    countdown: 3,            // seconds before recording starts (0 = off)
		    frameRate: 30,
		    maxWidth: 1920,          // compose-pipeline canvas width cap
		    videoBitsPerSecond: 6000000,
		    audioBitsPerSecond: 192000,
		    filePrefix: 'reelspot',
		  }
		
		  function isSupported() {
		    return typeof navigator !== 'undefined'
		      && !!navigator.mediaDevices
		      && typeof navigator.mediaDevices.getDisplayMedia === 'function'
		      && typeof MediaRecorder !== 'undefined'
		  }
		
		  /** Pick the best recording container: MP4 (Chrome/Edge 126+) first, WebM fallback. */
		  function pickFormat() {
		    if (typeof MediaRecorder === 'undefined') return { mime: '', ext: 'webm' }
		    for (const c of MIME_CANDIDATES) {
		      try { if (MediaRecorder.isTypeSupported(c.mime)) return c } catch (e) { /* keep looking */ }
		    }
		    return { mime: '', ext: 'webm' }
		  }
		
		  function stopStream(stream) {
		    if (!stream) return
		    try { stream.getTracks().forEach((t) => { try { t.stop() } catch (e) {} }) } catch (e) {}
		  }
		
		  function pad2(n) { return String(n).padStart(2, '0') }
		
		  function defaultName(prefix, ext, startedAt) {
		    const d = new Date(startedAt)
		    return prefix + '-' + d.getFullYear() + pad2(d.getMonth() + 1) + pad2(d.getDate())
		      + '-' + pad2(d.getHours()) + pad2(d.getMinutes()) + pad2(d.getSeconds()) + '.' + ext
		  }
		
		  function makeHiddenVideo(stream) {
		    const video = document.createElement('video')
		    video.muted = true
		    video.playsInline = true
		    video.style.display = 'none'
		    video.srcObject = stream
		    document.body.append(video)
		    return video
		  }
		
		  /**
		   * Compose pipeline: display track (+ optional webcam) -> hidden <video>s ->
		   * canvas (zoom transform, webcam bubble, cursor fx) -> captureStream.
		   *
		   * The cursor position is only knowable while the pointer is over THIS page,
		   * so cursor-follow zoom and cursor fx only track when recording this tab;
		   * for other windows the view stays at the wide shot (browser limitation).
		   */
		  async function createComposePipe(display, opts) {
		    const srcTrack = display.getVideoTracks()[0]
		    if (!srcTrack) return null
		    let w = 1920
		    let h = 1080
		    try {
		      const s = srcTrack.getSettings ? srcTrack.getSettings() : {}
		      if (s.width && s.height) { w = s.width; h = s.height }
		    } catch (e) {}
		    const scale = Math.min(1, opts.maxWidth / w)
		    w = Math.max(2, Math.round(w * scale))
		    h = Math.max(2, Math.round(h * scale))
		
		    const video = makeHiddenVideo(new MediaStream([srcTrack]))
		    try { await video.play() } catch (e) {}
		
		    // webcam bubble source
		    let cam = null
		    let camVideo = null
		    if (opts.webcam) {
		      try {
		        cam = await navigator.mediaDevices.getUserMedia({ video: { width: 1280 }, audio: false })
		        camVideo = makeHiddenVideo(cam)
		        try { await camVideo.play() } catch (e) {}
		      } catch (e) {
		        cam = null // webcam denied/unavailable — record without it
		      }
		    }
		
		    const canvas = document.createElement('canvas')
		    canvas.width = w
		    canvas.height = h
		    const g = canvas.getContext('2d')
		    if (!g) {
		      video.remove()
		      stopStream(cam)
		      if (camVideo) camVideo.remove()
		      return null
		    }
		
		    const st = {
		      zoom: 1, tzoom: 1, factor: opts.zoomFactor, factorAt: 0,
		      cx: w / 2, cy: h / 2, tx: w / 2, ty: h / 2,
		      lastMove: 0, cursorX: null, cursorY: null, ripples: [],
		    }
		    const toSource = (ev) => {
		      const iw = (typeof window !== 'undefined' && window.innerWidth) || w
		      const ih = (typeof window !== 'undefined' && window.innerHeight) || h
		      return [(ev.clientX / iw) * w, (ev.clientY / ih) * h]
		    }
		    const onMove = (ev) => {
		      const [sx, sy] = toSource(ev)
		      st.tx = sx
		      st.ty = sy
		      st.cursorX = sx
		      st.cursorY = sy
		      st.tzoom = st.factor
		      st.lastMove = Date.now()
		    }
		    // Alt+wheel: live zoom-factor control — down to 1x for the full page,
		    // up towards zoomMax for a closer follow (this-tab only, like the cursor)
		    const onWheel = (ev) => {
		      if (!ev.altKey) return
		      ev.preventDefault()
		      const dir = ev.deltaY < 0 ? 1 : -1
		      st.factor = Math.min(opts.zoomMax, Math.max(1, Math.round((st.factor + dir * opts.zoomStep) * 10) / 10))
		      st.tzoom = st.factor
		      st.lastMove = Date.now()
		      st.factorAt = Date.now()
		    }
		    const onDown = (ev) => {
		      const [sx, sy] = toSource(ev)
		      st.ripples.push({ x: sx, y: sy, t: Date.now() })
		      if (st.ripples.length > 12) st.ripples.shift()
		    }
		    const onLeave = () => { st.cursorX = null; st.cursorY = null }
		    document.addEventListener('mousemove', onMove)
		    document.addEventListener('mousedown', onDown)
		    document.addEventListener('mouseleave', onLeave)
		    if (opts.zoomWheel) document.addEventListener('wheel', onWheel, { passive: false })
		
		    const pipe = { video, camVideo, cam, canvas, raf: 0, stream: null, dead: false, detach: null, surface: '' }
		    pipe.detach = () => {
		      document.removeEventListener('mousemove', onMove)
		      document.removeEventListener('mousedown', onDown)
		      document.removeEventListener('mouseleave', onLeave)
		      if (opts.zoomWheel) document.removeEventListener('wheel', onWheel)
		    }
		
		    const draw = () => {
		      if (pipe.dead) return
		      if (Date.now() - st.lastMove > opts.zoomIdleMs) st.tzoom = 1
		      st.zoom += (st.tzoom - st.zoom) * 0.08
		      st.cx += (st.tx - st.cx) * 0.12
		      st.cy += (st.ty - st.cy) * 0.12
		      const vw = w / st.zoom
		      const vh = h / st.zoom
		      const cx = Math.min(Math.max(st.cx, vw / 2), w - vw / 2)
		      const cy = Math.min(Math.max(st.cy, vh / 2), h - vh / 2)
		      const sx0 = cx - vw / 2
		      const sy0 = cy - vh / 2
		      g.fillStyle = '#000'
		      g.fillRect(0, 0, w, h)
		      try { g.drawImage(video, sx0, sy0, vw, vh, 0, 0, w, h) } catch (e) {}
		
		      // webcam bubble
		      if (camVideo) {
		        const diameter = Math.round(w * opts.webcamSize)
		        const radius = diameter / 2
		        const margin = Math.round(diameter * 0.25)
		        const bx = opts.webcamPosition.indexOf('left') >= 0 ? margin + radius : w - margin - radius
		        const by = opts.webcamPosition.indexOf('top') >= 0 ? margin + radius : h - margin - radius
		        const cw = camVideo.videoWidth || 1280
		        const ch = camVideo.videoHeight || 720
		        const crop = Math.min(cw, ch)
		        g.save()
		        g.beginPath()
		        g.arc(bx, by, radius, 0, Math.PI * 2)
		        g.closePath()
		        g.clip()
		        g.fillStyle = '#000'
		        g.fillRect(bx - radius, by - radius, diameter, diameter)
		        if (opts.webcamMirror) {
		          g.translate(bx, by)
		          g.scale(-1, 1)
		          g.translate(-bx, -by)
		        }
		        try { g.drawImage(camVideo, (cw - crop) / 2, (ch - crop) / 2, crop, crop, bx - radius, by - radius, diameter, diameter) } catch (e) {}
		        g.restore()
		        g.beginPath()
		        g.arc(bx, by, radius, 0, Math.PI * 2)
		        g.lineWidth = Math.max(2, Math.round(diameter * 0.03))
		        g.strokeStyle = 'rgba(255,255,255,.9)'
		        g.stroke()
		      }
		
		      // cursor fx: highlight ring + click ripples (mapped through the zoom transform)
		      if (opts.cursorFx) {
		        const mapX = (x) => (x - sx0) * st.zoom
		        const mapY = (y) => (y - sy0) * st.zoom
		        if (st.cursorX !== null) {
		          g.beginPath()
		          g.arc(mapX(st.cursorX), mapY(st.cursorY), 14 * st.zoom, 0, Math.PI * 2)
		          g.lineWidth = 3
		          g.strokeStyle = 'rgba(255,213,74,.95)'
		          g.stroke()
		        }
		        const now = Date.now()
		        st.ripples = st.ripples.filter((r) => now - r.t < 600)
		        for (const r of st.ripples) {
		          const t = (now - r.t) / 600
		          g.beginPath()
		          g.arc(mapX(r.x), mapY(r.y), (8 + t * 46) * st.zoom, 0, Math.PI * 2)
		          g.lineWidth = 3 * (1 - t) + 1
		          g.strokeStyle = 'rgba(255,213,74,' + (0.9 * (1 - t)).toFixed(3) + ')'
		          g.stroke()
		        }
		      }
		
		      // Operator preview blit (every 2nd frame, canvas-to-canvas, no encoding).
		      // The minimap and the factor badge are OPERATOR aids: they are drawn
		      // here, onto the monitor canvas ONLY — never onto the recorded canvas,
		      // so they can never end up in the produced video.
		      if (pipe.previewCtx) {
		        pipe.previewFrame = (pipe.previewFrame || 0) + 1
		        if (pipe.previewFrame % 2 === 0) {
		          const p = pipe.previewCtx
		          const pw = pipe.previewW
		          const ph = pipe.previewH
		          try {
		            p.drawImage(canvas, 0, 0, pw, ph)
		            if (opts.zoomMinimap && st.zoom > 1.02) {
		              const mw = Math.round(pw * 0.3)
		              const mh = Math.round(ph * 0.3)
		              const mm = Math.max(6, Math.round(mw * 0.14))
		              const mx = pw - mm - mw
		              const my = mm
		              p.globalAlpha = 0.85
		              p.fillStyle = '#000'
		              p.fillRect(mx - 2, my - 2, mw + 4, mh + 4)
		              try { p.drawImage(video, mx, my, mw, mh) } catch (e) {}
		              p.globalAlpha = 1
		              p.lineWidth = 1.5
		              p.strokeStyle = 'rgba(255,255,255,.55)'
		              p.strokeRect(mx - 2, my - 2, mw + 4, mh + 4)
		              p.strokeStyle = 'rgba(255,213,74,.95)'
		              p.strokeRect(mx + (sx0 / w) * mw, my + (sy0 / h) * mh, (vw / w) * mw, (vh / h) * mh)
		            }
		            const label = st.zoom > 1.02 ? st.zoom.toFixed(1) + '×' : '全景 1.0×'
		            p.font = 'bold 13px system-ui, sans-serif'
		            const tw = p.measureText(label).width
		            p.fillStyle = 'rgba(0,0,0,.6)'
		            p.fillRect(8, ph - 27, tw + 12, 21)
		            p.fillStyle = '#ffd54a'
		            p.fillText(label, 14, ph - 12)
		          } catch (e) {}
		        }
		      }
		
		      pipe.raf = requestAnimationFrame(draw)
		    }
		    pipe.raf = requestAnimationFrame(draw)
		    try { pipe.stream = canvas.captureStream(opts.frameRate) } catch (e) { pipe.stream = null }
		    if (!pipe.stream) { destroyComposePipe(pipe); return null }
		
		    // remember the capture surface for the preview guard
		    try { pipe.surface = String(srcTrack.getSettings ? srcTrack.getSettings().displaySurface || '' : '') } catch (e) { pipe.surface = '' }
		    if (opts.operatorPreview && opts.previewWindow) attachPreview(pipe, opts.previewWindow)
		    else if (opts.previewWindow) closePreviewWindow(opts.previewWindow)
		    return pipe
		  }
		
		  /**
		   * Attach an in-page floating monitor: a fixed-position canvas overlay in the
		   * recording document. Fallback for when a Document PiP window cannot be
		   * opened (unsupported, blocked, or no transient activation left).
		   *
		   * Honest limitation: this overlay lives in the recorded document, so TAB
		   * capture DOES record it — there is no way to show pixels to the operator
		   * inside the very surface being captured without capturing them too.
		   * It is therefore refused for 'browser' capture unless the caller passes
		   * allowUnsafe. For 'window'/'monitor' capture of something else, the DSH
		   * tab is not the recorded surface, so the overlay stays private.
		   */
		  function attachInlineMonitor(pipe, doc, allowUnsafe) {
		    if (!pipe || !pipe.stream || !doc) return false
		    if (!allowUnsafe && pipe.surface === 'browser') return false
		    try {
		      const host = doc.createElement('div')
		      host.setAttribute('data-reelspot-monitor', '1')
		      host.style.cssText = [
		        'position:fixed', 'right:16px', 'bottom:16px', 'z-index:2147483647',
		        'width:320px', 'border-radius:10px', 'overflow:hidden',
		        'box-shadow:0 8px 28px rgba(0,0,0,.5)', 'border:1px solid rgba(255,255,255,.25)',
		        'background:#000', 'cursor:move', 'user-select:none',
		      ].join(';')
		      const pw = 320
		      const ph = Math.max(2, Math.round((pipe.canvas.height / pipe.canvas.width) * pw))
		      const pc = doc.createElement('canvas')
		      pc.width = pw
		      pc.height = ph
		      pc.style.cssText = 'display:block;width:100%;height:auto'
		      host.append(pc)
		      doc.body.append(host)
		
		      // drag to reposition
		      let dx = 0
		      let dy = 0
		      let dragging = false
		      const onDown = (ev) => {
		        dragging = true
		        const r = host.getBoundingClientRect()
		        dx = ev.clientX - r.left
		        dy = ev.clientY - r.top
		        ev.preventDefault()
		      }
		      const onMove = (ev) => {
		        if (!dragging) return
		        host.style.right = 'auto'
		        host.style.bottom = 'auto'
		        host.style.left = (ev.clientX - dx) + 'px'
		        host.style.top = (ev.clientY - dy) + 'px'
		      }
		      const onUp = () => { dragging = false }
		      host.addEventListener('mousedown', onDown)
		      doc.addEventListener('mousemove', onMove)
		      doc.addEventListener('mouseup', onUp)
		
		      pipe.previewCtx = pc.getContext('2d')
		      pipe.previewW = pw
		      pipe.previewH = ph
		      pipe.previewFrame = 0
		      pipe.previewHost = host
		      pipe.previewDetach = () => {
		        doc.removeEventListener('mousemove', onMove)
		        doc.removeEventListener('mouseup', onUp)
		        try { host.remove() } catch (e) {}
		      }
		      return true
		    } catch (e) {
		      return false
		    }
		  }
		
		  /**
		   * Attach the operator preview monitor to a running pipe: blit the composed
		   * canvas into a canvas inside a Document PiP window (frame blit, no media
		   * pipeline — MediaStream playback inside PiP documents renders black on
		   * some Chrome versions).
		   *
		   * Capture-surface safety:
		   *   'browser' (tab)    — safe: a PiP window is not part of the tab surface
		   *   'window'           — safe: window capture records that window's own
		   *                        surface, not other windows floating above it
		   *   'monitor' (screen) — UNSAFE on a single display: the monitor window sits
		   *                        on the captured screen. Allowed only when the
		   *                        caller passes allowUnsafe (operator can drag it to
		   *                        a second display).
		   */
		  function attachPreview(pipe, win, allowUnsafe) {
		    if (!pipe || !pipe.stream || !win) { closePreviewWindow(win); return false }
		    if (!allowUnsafe && pipe.surface === 'monitor') { closePreviewWindow(win); return false }
		    try {
		      const doc = win.document
		      doc.documentElement.style.cssText = 'height:100%;margin:0'
		      doc.body.style.cssText = 'height:100%;margin:0;background:#000;overflow:hidden'
		      const pc = doc.createElement('canvas')
		      const pw = 360
		      const ph = Math.max(2, Math.round((pipe.canvas.height / pipe.canvas.width) * pw))
		      pc.width = pw
		      pc.height = ph
		      pc.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;display:block;object-fit:contain;background:#000'
		      doc.body.append(pc)
		      pipe.previewCtx = pc.getContext('2d')
		      pipe.previewW = pw
		      pipe.previewH = ph
		      pipe.previewFrame = 0
		      pipe.previewWin = win
		      win.addEventListener('pagehide', () => { pipe.previewWin = null; pipe.previewCtx = null })
		      return true
		    } catch (e) {
		      closePreviewWindow(win)
		      return false
		    }
		  }
		
		  function closePreviewWindow(win) {
		    if (!win) return
		    try { win.close() } catch (e) {}
		  }
		
		  function destroyComposePipe(pipe) {
		    if (!pipe) return
		    pipe.dead = true
		    try { cancelAnimationFrame(pipe.raf) } catch (e) {}
		    try { pipe.detach() } catch (e) {}
		    if (pipe.previewDetach) { try { pipe.previewDetach() } catch (e) {} }
		    closePreviewWindow(pipe.previewWin)
		    stopStream(pipe.stream)
		    stopStream(pipe.cam)
		    try { pipe.video.srcObject = null; pipe.video.remove() } catch (e) {}
		    if (pipe.camVideo) { try { pipe.camVideo.srcObject = null; pipe.camVideo.remove() } catch (e) {} }
		  }
		
		  /**
		   * Create a recorder instance.
		   *
		   * @param {object} [options] see DEFAULTS
		   * @returns {{
		   *   start: () => Promise<{audioMode:string, zoomed:boolean, webcam:boolean, ext:string, mime:string} | null>,
		   *   stop: () => void,
		   *   pause: () => void,
		   *   resume: () => void,
		   *   getState: () => 'idle' | 'countdown' | 'recording' | 'paused',
		   *   on: (event: 'state' | 'countdown' | 'stop' | 'error', fn: Function) => () => void,
		   * }}
		   *
		   * Events:
		   *   'state'    -> 'idle' | 'countdown' | 'recording' | 'paused'
		   *   'countdown'-> remaining whole seconds (3, 2, 1)
		   *   'stop'     -> { blob, size, name, ext, mime, audioMode, zoomed, webcam, startedAt, durationMs }
		   *   'error'    -> Error (non-fatal, e.g. mic denied)
		   *
		   * start() resolves null when the user cancels the share picker or the countdown.
		   * stop() during the countdown cancels the recording.
		   * audioMode: 'system+mic' | 'system' | 'mic' | 'none'
		   *   ('system' = tab/system audio from getDisplayMedia; on Windows Chrome it is
		   *   only available for tab capture — that is a browser limitation.)
		   */
		  function createRecorder(options) {
		    const opts = Object.assign({}, DEFAULTS, options || {})
		    const listeners = { state: [], countdown: [], stop: [], error: [], monitor: [] }
		    const emit = (ev, arg) => {
		      listeners[ev].slice().forEach((fn) => { try { fn(arg) } catch (e) {} })
		    }
		    let active = null
		    let starting = false
		
		    function cleanupCapture(rec) {
		      destroyComposePipe(rec.pipe)
		      stopStream(rec.display)
		      stopStream(rec.mic)
		      if (rec.audioCtx) { try { rec.audioCtx.close() } catch (e) {} }
		    }
		
		    function netDurationMs(rec) {
		      const end = rec.phase === 'paused' && rec.pausedAt ? rec.pausedAt : Date.now()
		      return Math.max(0, end - rec.recordStartedAt - rec.pausedMs)
		    }
		
		    function finalize() {
		      const rec = active
		      if (!rec) return
		      active = null
		      cleanupCapture(rec)
		      const blob = new Blob(rec.chunks, { type: rec.mime || ('video/' + rec.ext) })
		      emit('state', 'idle')
		      if (!blob.size) return
		      emit('stop', {
		        blob,
		        size: blob.size,
		        name: defaultName(opts.filePrefix, rec.ext, rec.startedAt),
		        ext: rec.ext,
		        mime: rec.mime,
		        audioMode: rec.audioMode,
		        zoomed: rec.zoomed,
		        webcam: !!rec.webcam,
		        startedAt: rec.startedAt,
		        durationMs: netDurationMs(rec),
		      })
		    }
		
		    // rAF-based countdown (no timers — safe inside every sandbox)
		    function countdownWait(seconds, rec) {
		      return new Promise((resolve) => {
		        const start = Date.now()
		        let last = -1
		        const tick = () => {
		          if (rec.cancelled) { resolve(false); return }
		          const elapsed = (Date.now() - start) / 1000
		          const remaining = Math.ceil(seconds - elapsed)
		          if (elapsed >= seconds) { resolve(true); return }
		          if (remaining !== last) { last = remaining; emit('countdown', remaining) }
		          requestAnimationFrame(tick)
		        }
		        requestAnimationFrame(tick)
		      })
		    }
		
		    // re-entry lock: start() is async and `active` is only set AFTER the
		    // share picker resolves — a second call during that window would open
		    // another picker and tear down the first pipeline
		    async function start() {
		      if (active || starting) return null
		      starting = true
		      try {
		        return await startInner()
		      } finally {
		        starting = false
		      }
		    }
		
		    async function startInner() {
		      if (active) return null
		      if (!isSupported()) {
		        emit('error', new Error('ReelSpot: this browser does not support screen capture'))
		        return null
		      }
		      let display
		      try {
		        display = await navigator.mediaDevices.getDisplayMedia({
		          video: { frameRate: opts.frameRate },
		          audio: true,
		        })
		      } catch (e) {
		        return null // user cancelled the share picker
		      }
		
		      let mic = null
		      if (opts.mic) {
		        try {
		          mic = await navigator.mediaDevices.getUserMedia({
		            audio: { echoCancellation: true, noiseSuppression: true },
		          })
		        } catch (e) {
		          emit('error', new Error('ReelSpot: microphone unavailable, recording without it'))
		        }
		      }
		
		      const needsPipe = !!(opts.zoom || opts.cursorFx || opts.webcam)
		      let pipe = null
		      if (needsPipe) {
		        try { pipe = await createComposePipe(display, opts) } catch (e) { pipe = null }
		      }
		      if (opts.webcam && (!pipe || !pipe.cam)) {
		        emit('error', new Error('ReelSpot: webcam unavailable, recording without it'))
		      }
		      if (!pipe || !pipe.stream) closePreviewWindow(opts.previewWindow)
		
		      // Auto-open the operator monitor here: the share picker has just been
		      // confirmed, so the page may still hold transient activation, and this
		      // runs BEFORE the countdown so the monitor is live while framing.
		      // requestWindow() must never run before getDisplayMedia — it consumes
		      // the activation that the picker itself needs. Every failure is
		      // reported through 'monitor' so the UI can explain and offer a retry.
		      if (opts.operatorPreview && opts.autoMonitor && pipe && pipe.stream && !pipe.previewCtx) {
		        if (typeof documentPictureInPicture === 'undefined') {
		          emit('monitor', { ok: false, reason: 'unsupported', surface: pipe.surface })
		        } else if (pipe.surface === 'monitor') {
		          emit('monitor', { ok: false, reason: 'fullscreen', surface: pipe.surface })
		        } else {
		          try {
		            const win = await documentPictureInPicture.requestWindow({ width: 380, height: 240 })
		            const ok = attachPreview(pipe, win)
		            emit('monitor', { ok, reason: ok ? '' : 'attach-failed', surface: pipe.surface })
		          } catch (e) {
		            emit('monitor', {
		              ok: false,
		              reason: 'blocked',
		              surface: pipe.surface,
		              message: String(e && e.message ? e.message : e),
		            })
		          }
		        }
		      }
		
		      const hasSysAudio = display.getAudioTracks().length > 0
		      const recordStream = new MediaStream()
		      if (pipe && pipe.stream) pipe.stream.getVideoTracks().forEach((t) => recordStream.addTrack(t))
		      else display.getVideoTracks().forEach((t) => recordStream.addTrack(t))
		
		      let audioCtx = null
		      let audioMode = 'none'
		      if (mic && hasSysAudio && typeof AudioContext !== 'undefined') {
		        try {
		          audioCtx = new AudioContext()
		          if (audioCtx.resume) audioCtx.resume()
		          const dest = audioCtx.createMediaStreamDestination()
		          audioCtx.createMediaStreamSource(new MediaStream(display.getAudioTracks())).connect(dest)
		          audioCtx.createMediaStreamSource(mic).connect(dest)
		          dest.stream.getAudioTracks().forEach((t) => recordStream.addTrack(t))
		          audioMode = 'system+mic'
		        } catch (e) {
		          display.getAudioTracks().forEach((t) => recordStream.addTrack(t))
		          audioMode = 'system'
		        }
		      } else if (mic) {
		        mic.getAudioTracks().forEach((t) => recordStream.addTrack(t))
		        audioMode = 'mic'
		      } else if (hasSysAudio) {
		        display.getAudioTracks().forEach((t) => recordStream.addTrack(t))
		        audioMode = 'system'
		      }
		
		      const format = pickFormat()
		      let recorder
		      try {
		        recorder = new MediaRecorder(recordStream, format.mime
		          ? { mimeType: format.mime, videoBitsPerSecond: opts.videoBitsPerSecond, audioBitsPerSecond: opts.audioBitsPerSecond }
		          : undefined)
		      } catch (e) {
		        destroyComposePipe(pipe)
		        stopStream(display)
		        stopStream(mic)
		        if (audioCtx) { try { audioCtx.close() } catch (e2) {} }
		        emit('error', e)
		        return null
		      }
		
		      const rec = {
		        recorder, display, mic, audioCtx, pipe,
		        chunks: [], mime: format.mime, ext: format.ext,
		        startedAt: Date.now(), recordStartedAt: 0,
		        audioMode, zoomed: !!(pipe && pipe.stream && opts.zoom),
		        webcam: !!(pipe && pipe.cam),
		        phase: 'countdown', cancelled: false,
		        pausedMs: 0, pausedAt: 0,
		      }
		      active = rec
		      recorder.ondataavailable = (ev) => { if (ev.data && ev.data.size) rec.chunks.push(ev.data) }
		      recorder.onstop = () => finalize()
		      const vt = display.getVideoTracks()[0]
		      if (vt) vt.onended = () => stop() // browser "stop sharing" UI
		
		      // countdown before the recorder starts rolling
		      if (opts.countdown > 0) {
		        emit('state', 'countdown')
		        const proceed = await countdownWait(opts.countdown, rec)
		        if (!proceed || active !== rec) {
		          if (active === rec) active = null
		          cleanupCapture(rec)
		          emit('state', 'idle')
		          return null
		        }
		      }
		
		      recorder.start(1000)
		      rec.recordStartedAt = Date.now()
		      rec.phase = 'recording'
		      emit('state', 'recording')
		      return { audioMode, zoomed: rec.zoomed, webcam: rec.webcam, ext: format.ext, mime: format.mime }
		    }
		
		    function stop() {
		      const rec = active
		      if (!rec) return
		      if (rec.phase === 'countdown') { rec.cancelled = true; return }
		      try { rec.recorder.stop() } catch (e) { finalize() } // onstop -> finalize
		    }
		
		    function pause() {
		      const rec = active
		      if (!rec || rec.phase !== 'recording') return
		      try {
		        rec.recorder.pause()
		        rec.phase = 'paused'
		        rec.pausedAt = Date.now()
		        emit('state', 'paused')
		      } catch (e) {}
		    }
		
		    function resume() {
		      const rec = active
		      if (!rec || rec.phase !== 'paused') return
		      try {
		        rec.recorder.resume()
		        rec.pausedMs += Date.now() - rec.pausedAt
		        rec.pausedAt = 0
		        rec.phase = 'recording'
		        emit('state', 'recording')
		      } catch (e) {}
		    }
		
		    function getState() { return active ? active.phase : 'idle' }
		
		    /**
		     * Attach a Document PiP monitor window to the RUNNING recorder.
		     * Call from a user gesture (requestWindow consumes transient activation,
		     * so it cannot be opened around getDisplayMedia). Returns whether the
		     * preview is now live; the window is closed when not usable.
		     */
		    function attachPreviewWindow(win, allowUnsafe) {
		      const rec = active
		      if (!rec || !rec.pipe) { closePreviewWindow(win); return false }
		      return attachPreview(rec.pipe, win, allowUnsafe)
		    }
		
		    /**
		     * Fallback monitor rendered inside the page itself (no PiP required).
		     * Pass allowUnsafe to accept that TAB capture records the overlay too.
		     */
		    function attachInlineMonitorNow(allowUnsafe) {
		      const rec = active
		      if (!rec || !rec.pipe) return false
		      if (rec.pipe.previewCtx) return true
		      return attachInlineMonitor(rec.pipe, typeof document !== 'undefined' ? document : null, allowUnsafe)
		    }
		
		    /** Remove whichever monitor is currently attached. */
		    function detachMonitor() {
		      const rec = active
		      if (!rec || !rec.pipe) return
		      if (rec.pipe.previewDetach) { try { rec.pipe.previewDetach() } catch (e) {} }
		      closePreviewWindow(rec.pipe.previewWin)
		      rec.pipe.previewDetach = null
		      rec.pipe.previewWin = null
		      rec.pipe.previewCtx = null
		    }
		
		    /** Whether the operator monitor is currently attached and live. */
		    function hasMonitor() {
		      return !!(active && active.pipe && active.pipe.previewCtx)
		    }
		
		    /** Capture surface of the running recording: 'browser' | 'window' | 'monitor' | ''. */
		    function getSurface() {
		      return active && active.pipe ? (active.pipe.surface || '') : ''
		    }
		
		    function on(ev, fn) {
		      if (!listeners[ev] || typeof fn !== 'function') return () => {}
		      listeners[ev].push(fn)
		      return () => {
		        const i = listeners[ev].indexOf(fn)
		        if (i >= 0) listeners[ev].splice(i, 1)
		      }
		    }
		
		    return { start, stop, pause, resume, getState, attachPreviewWindow, attachInlineMonitorNow, detachMonitor, hasMonitor, getSurface, on }
		  }
		
		  return { createRecorder, pickFormat, isSupported }
		  })()
		/*
		 * ReelSpot — DSH composition plugin, CLIENT bundle body.
		 *
		 * This source is written for the composition-plugin module format (NOT the
		 * dynamic-plugin sandbox): build.mjs wraps it into dsh/lib/client.js as
		 *
		 *   window.__ModuleLoader__.load({ id: 'dsh-reelspot', factory: (require) => {
		 *     const React = require('react')
		 *     const ReelSpot = (() => { ...core... })()
		 *     ...this file...
		 *   } })
		 *
		 * Inside the factory: real browser globals (fetch/document/window) and a real
		 * cordis ctx (ctx.slots, ctx.effect, timer mixin via inject: ['timer']).
		 * Plain JavaScript only — no JSX, no imports.
		 */
		
		const CSS = [
		  '.reelspot-wrap{display:inline-flex;align-items:center;gap:4px}',
		  '.reelspot-btn{display:inline-flex;align-items:center;gap:6px;height:28px;padding:0 10px;border-radius:14px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.45));background:transparent;color:inherit;font-size:12px;line-height:1;cursor:pointer;user-select:none;font-family:inherit}',
		  '.reelspot-btn:hover{background:rgba(127,127,127,.12)}',
		  '.reelspot-dot{width:8px;height:8px;border-radius:50%;background:#e5484d;flex:none}',
		  '.reelspot-btn.recording{border-color:#e5484d;color:#e5484d;font-variant-numeric:tabular-nums}',
		  '.reelspot-btn.recording .reelspot-dot{animation:reelspot-pulse 1.2s ease-in-out infinite}',
		  '.reelspot-btn.paused{border-color:var(--dsw-alias-state-warn-primary,#e6a23c);color:var(--dsw-alias-state-warn-primary,#e6a23c);font-variant-numeric:tabular-nums}',
		  '.reelspot-btn.countdown{border-color:var(--dsw-alias-brand-primary,#4f7cff);color:var(--dsw-alias-brand-primary,#4f7cff);font-weight:700}',
		  '@keyframes reelspot-pulse{0%,100%{opacity:1}50%{opacity:.25}}',
		  '.reelspot-tog{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:14px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.45));background:transparent;color:inherit;font-size:13px;cursor:pointer;user-select:none;font-family:inherit}',
		  '.reelspot-tog:hover{background:rgba(127,127,127,.12)}',
		  '.reelspot-tog.off{opacity:.4}',
		  '.reelspot-tog.on{border-color:var(--dsw-alias-brand-primary,#4f7cff);color:var(--dsw-alias-brand-primary,#4f7cff)}',
		  '.reelspot-tog[disabled]{opacity:.35;cursor:default}',
		  '.reelspot-badge{background:#e5484d;color:#fff;border-radius:8px;min-width:16px;height:16px;font-size:10px;display:inline-flex;align-items:center;justify-content:center;padding:0 4px}',
		  '.reelspot-panel{position:fixed;top:56px;right:12px;z-index:9999;width:340px;max-height:72vh;overflow:auto;background:var(--dsw-alias-bg-overlay,#222);color:var(--dsw-alias-label-primary,#eee);border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.4));border-radius:10px;box-shadow:0 10px 32px rgba(0,0,0,.35);padding:10px;font-size:12px;font-family:inherit}',
		  '.reelspot-panel-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;font-weight:600}',
		  '.reelspot-x{background:none;border:none;color:inherit;font-size:16px;cursor:pointer;line-height:1;padding:2px 6px}',
		  '.reelspot-item{margin-bottom:12px;padding-bottom:10px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.25))}',
		  '.reelspot-item:last-child{margin-bottom:0;padding-bottom:0;border-bottom:none}',
		  '.reelspot-video{width:100%;border-radius:6px;background:#000;display:block}',
		  '.reelspot-meta{color:var(--dsw-alias-label-secondary,#999);margin:6px 0;word-break:break-all}',
		  '.reelspot-ops{display:flex;gap:6px;flex-wrap:wrap}',
		  '.reelspot-op{padding:4px 10px;border-radius:6px;border:1px solid var(--dsw-alias-border-l1,rgba(127,127,127,.4));background:transparent;color:inherit;cursor:pointer;text-decoration:none;font-size:12px;font-family:inherit}',
		  '.reelspot-op:hover{background:rgba(127,127,127,.15)}',
		  '.reelspot-op[disabled]{opacity:.5;cursor:default}',
		  '.reelspot-path{margin-top:6px;color:var(--dsw-alias-state-success-primary,#4caf50);word-break:break-all}',
		  '.reelspot-err{margin-top:6px;color:var(--dsw-alias-state-error-primary,#e5484d);word-break:break-all}',
		  '.reelspot-warn{font-size:11px;color:var(--dsw-alias-state-warn-primary,#e6a23c);max-width:170px;line-height:1.35}',
		].join('\n')
		
		// map core error messages to short inline Chinese warnings
		function warnText(e) {
		  const m = String(e && e.message ? e.message : e)
		  if (m.indexOf('webcam') >= 0) return '⚠️ 摄像头不可用，本次录制不含摄像头'
		  if (m.indexOf('microphone') >= 0) return '⚠️ 麦克风不可用，本次录制无麦克风声音'
		  if (m.indexOf('support') >= 0) return '⚠️ 当前浏览器不支持录屏'
		  return '⚠️ ' + m.slice(0, 80)
		}
		
		function pad2(n) { return String(n).padStart(2, '0') }
		
		function fmtSize(bytes) {
		  if (bytes >= 1048576) return (bytes / 1048576).toFixed(1) + ' MB'
		  if (bytes >= 1024) return (bytes / 1024).toFixed(0) + ' KB'
		  return bytes + ' B'
		}
		
		function toBase64(blob) {
		  return new Promise((resolve, reject) => {
		    const r = new FileReader()
		    r.onload = () => {
		      const s = String(r.result || '')
		      resolve(s.slice(s.indexOf(',') + 1))
		    }
		    r.onerror = () => reject(r.error || new Error('read failed'))
		    r.readAsDataURL(blob)
		  })
		}
		
		const audioText = (mode) => mode === 'system+mic' ? '系统+麦克风'
		  : mode === 'mic' ? '麦克风'
		  : mode === 'system' ? '系统/标签页'
		  : '无音频'
		
		let nextId = 1
		
		// set by the mounted component so the global keyboard shortcut can reach it
		const shortcutToggleRef = { current: null }
		
		function ReelSpotButton(ctx) {
		  return function ReelSpotButtonView() {
		    const [state, setState] = React.useState('idle') // idle | countdown | recording | paused
		    const [countNum, setCountNum] = React.useState(3)
		    const [elapsed, setElapsed] = React.useState(0)
		    const [micOn, setMicOn] = React.useState(true)
		    const [zoomOn, setZoomOn] = React.useState(false)
		    const [webcamOn, setWebcamOn] = React.useState(false)
		    const [cursorFxOn, setCursorFxOn] = React.useState(false)
		    const [items, setItems] = React.useState([]) // {id,name,ext,url,blob,size,audioMode,zoomed,webcam,savedPath,saving,transcoding,transcodedPath,error}
		    const [warn, setWarn] = React.useState('')
		    const [canMonitor, setCanMonitor] = React.useState(false) // compose pipeline + PiP support
		    const [panelOpen, setPanelOpen] = React.useState(false)
		    const recRef = React.useRef(null) // ReelSpot recorder instance
		    const startRef = React.useRef(false) // start-in-flight guard (picker open / countdown)
		    const elapsedBaseRef = React.useRef(0)
		    const micRef = React.useRef(true)
		    const zoomRef = React.useRef(false)
		    const webcamRef = React.useRef(false)
		    const cursorFxRef = React.useRef(false)
		    const itemsRef = React.useRef([])
		    const stateRef = React.useRef('idle')
		    micRef.current = micOn
		    zoomRef.current = zoomOn
		    webcamRef.current = webcamOn
		    cursorFxRef.current = cursorFxOn
		    itemsRef.current = items
		    stateRef.current = state
		
		    const patchItem = (id, patch) => {
		      setItems((prev) => prev.map((it) => (it.id === id ? Object.assign({}, it, patch) : it)))
		    }
		
		    const start = async () => {
		      if (startRef.current) return
		      startRef.current = true
		      const composeOn = zoomRef.current || cursorFxRef.current || webcamRef.current
		      setCanMonitor(!!composeOn && typeof documentPictureInPicture !== 'undefined')
		      const recorder = ReelSpot.createRecorder({
		        mic: micRef.current,
		        zoom: zoomRef.current,
		        webcam: webcamRef.current,
		        cursorFx: cursorFxRef.current,
		        countdown: 3,
		      })
		      recRef.current = recorder
		      recorder.on('countdown', (n) => setCountNum(n))
		      recorder.on('stop', (result) => {
		        recRef.current = null
		        setState('idle')
		        setCanMonitor(false)
		        setElapsed(0)
		        elapsedBaseRef.current = 0
		        const item = {
		          id: nextId++,
		          name: result.name,
		          ext: result.ext,
		          blob: result.blob,
		          url: URL.createObjectURL(result.blob),
		          size: result.size,
		          audioMode: result.audioMode,
		          zoomed: result.zoomed,
		          webcam: result.webcam,
		          savedPath: '',
		          saving: false,
		          transcoding: false,
		          transcodedPath: '',
		          error: '',
		        }
		        setItems((prev) => [item].concat(prev))
		        setPanelOpen(true)
		      })
		      recorder.on('state', (s) => {
		        if (s === 'recording') setState('recording')
		        else if (s === 'paused') {
		          elapsedBaseRef.current = elapsedRefNow()
		          setState('paused')
		        } else if (s === 'countdown') setState('countdown')
		        else if (s === 'idle') { setState('idle'); setCanMonitor(false) }
		      })
		      recorder.on('error', (e) => {
		        console.error('ReelSpot:', e && e.message ? e.message : e)
		        setWarn(warnText(e))
		        ctx.timeout(() => setWarn(''), 5000)
		      })
		      // monitor outcome: explain the failure and fall back to the in-page
		      // floating monitor so an operator always gets a live view
		      recorder.on('monitor', (info) => {
		        console.log('ReelSpot monitor:', info)
		        if (info.ok) { setCanMonitor(false); return }
		        setCanMonitor(true)
		        // in-page fallback is only private when the recorded surface is NOT
		        // this tab; for tab capture it would land in the video, so we only
		        // offer it behind the explicit 🖥️ button
		        if (info.surface !== 'browser' && recorder.attachInlineMonitorNow(false)) {
		          setCanMonitor(false)
		          setWarn('ℹ️ 悬浮窗打开失败，已改用页内监视框')
		        } else if (info.reason === 'unsupported') {
		          setWarn('⚠️ 浏览器不支持悬浮监视窗')
		        } else {
		          setWarn('⚠️ 监视窗未自动打开（' + info.reason + '），点 🖥️ 打开')
		        }
		        ctx.timeout(() => setWarn(''), 8000)
		      })
		      const begun = await recorder.start()
		      if (!begun && recorder.getState() === 'idle') {
		        recRef.current = null
		        setState('idle') // picker or countdown cancelled
		        setCanMonitor(false)
		      } else if (begun) {
		        // monitor outcome is reported through the 'monitor' event above
		        if (recorder.hasMonitor()) setCanMonitor(false)
		      }
		      startRef.current = false
		    }
		
		    // operator monitor: opened from THIS click (requestWindow consumes the
		    // transient activation, so it must not be opened around getDisplayMedia)
		    const openMonitor = async () => {
		      const recorder = recRef.current
		      if (!recorder || typeof documentPictureInPicture === 'undefined') {
		        // no PiP at all — in-page monitor is the only option
		        const rec = recRef.current
		        if (rec && rec.attachInlineMonitorNow(true)) setCanMonitor(false)
		        return
		      }
		      try {
		        const win = await documentPictureInPicture.requestWindow({ width: 380, height: 240 })
		        // allowUnsafe: an explicit click means the operator accepts that a
		        // full-screen recording will contain the monitor unless moved off-screen
		        if (recorder.attachPreviewWindow(win, true)) setCanMonitor(false)
		        else {
		          setWarn('⚠️ 监视窗打开失败（录制已结束？）')
		          ctx.timeout(() => setWarn(''), 5000)
		        }
		      } catch (e) {
		        // PiP refused even on a direct click — use the in-page monitor
		        if (recorder.attachInlineMonitorNow(true)) {
		          setCanMonitor(false)
		          setWarn('ℹ️ 已改用页内监视框')
		        } else {
		          setWarn('⚠️ 监视窗打开失败：' + String(e && e.message ? e.message : e).slice(0, 60))
		        }
		        ctx.timeout(() => setWarn(''), 6000)
		      }
		    }
		
		    const stop = () => {
		      const recorder = recRef.current
		      if (recorder) recorder.stop()
		    }
		
		    const pauseOrResume = () => {
		      const recorder = recRef.current
		      if (!recorder) return
		      if (recorder.getState() === 'paused') recorder.resume()
		      else recorder.pause()
		    }
		
		    // elapsed helpers: accumulated base (pause) + live segment (ticker)
		    let elapsedRefNow = () => elapsed
		    React.useEffect(() => { elapsedRefNow = () => elapsed })
		
		    // elapsed ticker while actively recording (frozen while paused)
		    React.useEffect(() => {
		      if (state !== 'recording') return undefined
		      const segStart = Date.now()
		      return ctx.interval(() => {
		        setElapsed(elapsedBaseRef.current + Math.floor((Date.now() - segStart) / 1000))
		      }, 500)
		    }, [state])
		
		    // expose start/stop toggle to the global keyboard shortcut
		    React.useEffect(() => {
		      shortcutToggleRef.current = () => {
		        const s = stateRef.current
		        if (s === 'recording' || s === 'paused' || s === 'countdown') stop()
		        else start()
		      }
		      return () => { shortcutToggleRef.current = null }
		    })
		
		    // unmount cleanup: halt capture, revoke URLs
		    React.useEffect(() => () => {
		      const recorder = recRef.current
		      if (recorder) { recRef.current = null; try { recorder.stop() } catch (e) {} }
		      itemsRef.current.forEach((it) => { try { URL.revokeObjectURL(it.url) } catch (e) {} })
		    }, [])
		
		    const saveToWorkspace = async (item) => {
		      patchItem(item.id, { saving: true, error: '' })
		      try {
		        const base64 = await toBase64(item.blob)
		        const res = await fetch('/dsh-reelspot/save', {
		          method: 'POST',
		          headers: { 'content-type': 'application/json' },
		          body: JSON.stringify({ name: item.name, base64 }),
		        })
		        const data = await res.json()
		        if (data && data.ok) patchItem(item.id, { saving: false, savedPath: String(data.path || '') })
		        else patchItem(item.id, { saving: false, error: '保存失败: ' + (data && data.error ? data.error : 'HTTP ' + res.status) })
		      } catch (e) {
		        patchItem(item.id, { saving: false, error: '保存失败: ' + String(e && e.message ? e.message : e) })
		      }
		    }
		
		    const transcode = async (item) => {
		      patchItem(item.id, { transcoding: true, error: '' })
		      try {
		        const base64 = await toBase64(item.blob)
		        const res = await fetch('/dsh-reelspot/transcode', {
		          method: 'POST',
		          headers: { 'content-type': 'application/json' },
		          body: JSON.stringify({ name: item.name, base64 }),
		        })
		        const data = await res.json()
		        if (data && data.ok) patchItem(item.id, { transcoding: false, transcodedPath: String(data.path || '') })
		        else patchItem(item.id, { transcoding: false, error: '转码失败: ' + (data && data.error ? data.error : 'HTTP ' + res.status) })
		      } catch (e) {
		        patchItem(item.id, { transcoding: false, error: '转码失败: ' + String(e && e.message ? e.message : e) })
		      }
		    }
		
		    const removeItem = (item) => {
		      try { URL.revokeObjectURL(item.url) } catch (e) {}
		      setItems((prev) => prev.filter((it) => it.id !== item.id))
		    }
		
		    const busy = state !== 'idle'
		    const recording = state === 'recording'
		    const paused = state === 'paused'
		    const counting = state === 'countdown'
		
		    const tog = (on, setOn, title, icon) => React.createElement('button', {
		      className: 'reelspot-tog' + (on ? ' on' : ' off'),
		      title,
		      disabled: busy,
		      onClick: () => setOn(!on),
		    }, icon)
		
		    const label = counting ? String(countNum)
		      : (recording || paused)
		        ? pad2(Math.floor(elapsed / 60)) + ':' + pad2(elapsed % 60)
		        : '录屏'
		
		    const mainButton = React.createElement('button', {
		      className: 'reelspot-btn' + (recording ? ' recording' : '') + (paused ? ' paused' : '') + (counting ? ' countdown' : ''),
		      title: counting ? '倒计时中，点击取消'
		        : recording ? '停止录屏 (Alt+Shift+R)'
		        : paused ? '已暂停，点击停止'
		        : items.length
		          ? '开始录屏 (Alt+Shift+R)；点击查看已录 ' + items.length + ' 段视频'
		          : '开始录屏 (Alt+Shift+R)：选择屏幕 / 窗口 / 标签页',
		      onClick: () => {
		        if (counting) { stop(); return }
		        if (recording || paused) { stop(); return }
		        if (items.length && !panelOpen) { setPanelOpen(true); return }
		        start()
		      },
		    },
		      React.createElement('span', { className: 'reelspot-dot' }),
		      label,
		      !busy && items.length
		        ? React.createElement('span', { className: 'reelspot-badge' }, String(items.length))
		        : null,
		    )
		
		    const pauseButton = (recording || paused)
		      ? React.createElement('button', {
		          className: 'reelspot-tog',
		          title: paused ? '继续录制' : '暂停录制',
		          onClick: pauseOrResume,
		        }, paused ? '▶' : '⏸')
		      : null
		
		    const panel = panelOpen && items.length
		      ? React.createElement('div', { className: 'reelspot-panel' },
		          React.createElement('div', { className: 'reelspot-panel-head' },
		            React.createElement('span', null, '录制完成 (' + items.length + ')'),
		            React.createElement('button', { className: 'reelspot-x', title: '关闭', onClick: () => setPanelOpen(false) }, '×'),
		          ),
		          items.map((it) => React.createElement('div', { className: 'reelspot-item', key: it.id },
		            React.createElement('video', { className: 'reelspot-video', src: it.url, controls: true, preload: 'metadata' }),
		            React.createElement('div', { className: 'reelspot-meta' },
		              it.name + ' · ' + fmtSize(it.size) + ' · ' + audioText(it.audioMode)
		              + (it.zoomed ? ' · 聚焦' : '') + (it.webcam ? ' · 摄像头' : '')),
		            React.createElement('div', { className: 'reelspot-ops' },
		              React.createElement('a', { className: 'reelspot-op', href: it.url, download: it.name }, '下载'),
		              React.createElement('button', {
		                className: 'reelspot-op',
		                disabled: it.saving || !!it.savedPath,
		                onClick: () => saveToWorkspace(it),
		              }, it.saving ? '保存中…' : it.savedPath ? '已存到工作区' : '存到工作区'),
		              it.ext === 'webm'
		                ? React.createElement('button', {
		                    className: 'reelspot-op',
		                    disabled: it.transcoding || !!it.transcodedPath,
		                    title: '需要主机安装 ffmpeg',
		                    onClick: () => transcode(it),
		                  }, it.transcoding ? '转码中…' : it.transcodedPath ? '已转 MP4' : '转 MP4')
		                : null,
		              React.createElement('button', { className: 'reelspot-op', onClick: () => removeItem(it) }, '删除'),
		            ),
		            it.savedPath ? React.createElement('div', { className: 'reelspot-path' }, it.savedPath) : null,
		            it.transcodedPath ? React.createElement('div', { className: 'reelspot-path' }, it.transcodedPath) : null,
		            it.error ? React.createElement('div', { className: 'reelspot-err' }, it.error) : null,
		          )),
		        )
		      : null
		
		    return React.createElement(React.Fragment, null,
		      React.createElement('span', { className: 'reelspot-wrap' },
		        tog(cursorFxOn, setCursorFxOn, cursorFxOn ? '光标高亮+点击波纹：开（仅录本标签页时跟踪）' : '光标高亮+点击波纹：关（点击开启）', '🖱️'),
		        tog(zoomOn, setZoomOn, zoomOn ? '放大聚焦：开（录制中 Alt+滚轮调倍数，滚到 1× 看整页；点击关闭）' : '放大聚焦：关（点击开启，光标移动自动跟随放大）', '🔍'),
		        tog(webcamOn, setWebcamOn, webcamOn ? '摄像头气泡：开（点击关闭）' : '摄像头气泡：关（点击开启）', '📹'),
		        tog(micOn, setMicOn, micOn ? '麦克风：开（点击关闭）' : '麦克风：关（点击开启）', '🎤'),
		        pauseButton,
		        (recording || paused) && canMonitor
		          ? React.createElement('button', {
		              className: 'reelspot-tog',
		              title: '打开监视窗：悬浮小窗实时显示录制画面和取景范围（不会被录进视频）',
		              onClick: openMonitor,
		            }, '🖥️')
		          : null,
		        mainButton,
		        warn ? React.createElement('span', { className: 'reelspot-warn' }, warn) : null,
		      ),
		      panel,
		    )
		  }
		}
		
		function apply(ctx) {
		  // package-owned stylesheet, removed with the plugin fiber
		  ctx.effect(() => {
		    const tag = document.createElement('style')
		    tag.dataset.plugin = 'dsh-reelspot'
		    tag.textContent = CSS
		    document.head.append(tag)
		    return () => tag.remove()
		  }, 'dsh-reelspot: styles')
		
		  // global keyboard shortcut: Alt+Shift+R toggles recording
		  ctx.effect(() => {
		    const handler = (e) => {
		      if (e.altKey && e.shiftKey && (e.key === 'R' || e.key === 'r')) {
		        e.preventDefault()
		        if (shortcutToggleRef.current) shortcutToggleRef.current()
		      }
		    }
		    document.addEventListener('keydown', handler)
		    return () => document.removeEventListener('keydown', handler)
		  }, 'dsh-reelspot: shortcut')
		
		  const View = ReelSpotButton(ctx)
		  ctx.slots.inject('conversation.session.header.actions', () => ctx.slots.register(
		    { name: 'conversation.session.header.actions', id: 'reelspot', order: 30, label: 'ReelSpot 录屏' },
		    () => React.createElement(View),
		  ))
		}
		
		exports.name = 'dsh-reelspot'
		exports.inject = ['slots', 'timer']
		exports.apply = apply

		return module.exports;
	}
});
