/*
 * Build the DSH plugin artifacts.
 *
 *   node build.mjs
 *
 * Outputs:
 *   dist/reelspot-dsh.client.js  — dynamic-plugin client half (cordis_define code.client)
 *   dist/reelspot-dsh.host.js    — dynamic-plugin host half (cordis_define code.host)
 *   dsh/lib/client.js            — composition-plugin client bundle
 *                                  (lazy CJS format for the dsh.client module table)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(fileURLToPath(import.meta.url))
const core = readFileSync(join(root, 'src', 'reelspot.js'), 'utf8')
const m = core.match(/\/\/ __CORE_BEGIN__([\s\S]*?)\/\/ __CORE_END__/)
if (!m) throw new Error('core markers (__CORE_BEGIN__/__CORE_END__) not found in src/reelspot.js')

const client = readFileSync(join(root, 'src', 'dsh-plugin', 'client.js'), 'utf8')
const host = readFileSync(join(root, 'src', 'dsh-plugin', 'host.js'), 'utf8')
const bundle = readFileSync(join(root, 'src', 'dsh-plugin', 'client.bundle.js'), 'utf8')

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(
  join(root, 'dist', 'reelspot-dsh.client.js'),
  '// ReelSpot DSH plugin — CLIENT half (generated by build.mjs; do not edit directly)\n'
    + 'const ReelSpot = (() => {' + m[1] + '})()\n\n' + client,
)
writeFileSync(
  join(root, 'dist', 'reelspot-dsh.host.js'),
  '// ReelSpot DSH plugin — HOST half (generated by build.mjs; do not edit directly)\n' + host,
)

// Composition-plugin client bundle: lazy CJS module-table format.
// React comes from the shell seed table; the core is inlined; the bundle body
// assigns exports.{name,inject,apply} and returns module.exports.
mkdirSync(join(root, 'dsh', 'lib'), { recursive: true })
writeFileSync(
  join(root, 'dsh', 'lib', 'client.js'),
  '// dsh-reelspot client bundle (generated by build.mjs; do not edit directly)\n'
    + 'window.__ModuleLoader__.load({\n'
    + '\tid: "dsh-reelspot",\n'
    + '\tfactory: (require) => {\n'
    + '\t\tvar module = { exports: {} };\n'
    + '\t\tvar exports = module.exports;\n'
    + '\t\tconst React = require("react");\n'
    + '\t\tconst ReelSpot = (() => {' + m[1].replace(/\n/g, '\n\t\t') + '})()\n'
    + bundle.split('\n').map((line) => (line.length ? '\t\t' + line : line)).join('\n') + '\n'
    + '\t\treturn module.exports;\n'
    + '\t}\n'
    + '});\n',
)

console.log('written: dist/reelspot-dsh.client.js, dist/reelspot-dsh.host.js, dsh/lib/client.js')
