/*
 * Build the DSH dynamic-plugin halves.
 *
 *   node build.mjs
 *
 * Outputs:
 *   dist/reelspot-dsh.client.js  — ReelSpot core inlined + client UI shell,
 *                                  ready to paste into cordis_define code.client
 *   dist/reelspot-dsh.host.js    — host half, ready for cordis_define code.host
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(fileURLToPath(import.meta.url))
const core = readFileSync(join(root, 'src', 'reelspot.js'), 'utf8')
const m = core.match(/\/\/ __CORE_BEGIN__([\s\S]*?)\/\/ __CORE_END__/)
if (!m) throw new Error('core markers (__CORE_BEGIN__/__CORE_END__) not found in src/reelspot.js')

const client = readFileSync(join(root, 'src', 'dsh-plugin', 'client.js'), 'utf8')
const host = readFileSync(join(root, 'src', 'dsh-plugin', 'host.js'), 'utf8')

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(
  join(root, 'dist', 'reelspot-dsh.client.js'),
  '// ReelSpot DSH plugin — CLIENT half (generated by build.mjs; do not edit directly)\n'
    + 'const ReelSpot = (() => {' + m[1] + '})()\n\n' + client,
)
writeFileSync(
  join(root, 'dist', 'reelspot-dsh.host.js'),
  '// ReelSpot DSH plugin — HOST half (generated by build.mjs; do not edit directly)\n' + host,
)
console.log('written: dist/reelspot-dsh.client.js, dist/reelspot-dsh.host.js')
